[package]
name = "domain_list_builder"
version = "0.1.0"
authors = ["Alex Williams <hughaw64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockconvert = "0.1"

reqwest = {version = "0.10", features = ["rustls-tls", "gzip", "brotli", "json"]}
futures = {version = "0.3"}
tokio = {version = "0.2", features =["macros"]}
rand = "0.7"
serde = {version = "1.0", features = ["derive"]}
lazy_static = "1.4"
async-std = "1.6"
tokio-tungstenite = {version = "0.10", features = ["tls"]}

csv = "1.1"
serde_json = "1.0"

regex = "1.3"

chrono = "0.4"
filetime = "0.2"

clap = "3.0.0-beta.1"
stacker = "0.1.11"

[profile.release]
debug = true